version: '3.8'

services:
  # Frontend Service (TypeScript/React/Vue/Angular)
  frontend:
    build:
      context: 
      dockerfile: 
    ports:
    volumes:
    environment:
    depends_on:
    networks:

  # GetWay service  
  Getway:
    build:
      context: 
      dockerfile: 
    ports:
    volumes:
    environment:
    depends_on:
    networks:

  # Backend Service  

  # Web Server (Nginx)
  
  # Database (MySQL/MariaDB - opcional se usar banco de dados)
  

  # WebSocket Server (opcional para jogo em tempo real)
  

volumes:
  pong_db_data:
    driver: local
    driver_opts:
      type: none
      device: /goinfre/pong_db_data # Ajuste para /sgoinfre se necessário
      o: bind

networks:
  pong-network:
    driver: bridge