version : "3.9"
services :
  front:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: frontend_prod:local
    volumes:
      - front:/app/build
    networks:
      - pongnet
    init: true


  nginx :
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    image: nginx_prod:local
    networks:
      - pongnet
    volumes :
      - front:/var/www/html/
    ports:
      - 8000:80
    init: true
    restart: always

volumes: 
  front:
  database:

networks:
  pongnet:
  