services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - transcendence_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    
networks:
  transcendence_network:
    driver: bridge